home_one = {
    "id": 1,
    "property_address": "4974 Johanna Forks, Shainafort, CT 572476",
    "property_identifier": "4974+Johanna+Forks&zipcode=572476",
    "property": {
        "air_conditioning": "yes",
        "attic": "false",
        "basement": "full_basement",
        "building_area_sq_ft": 1824,
        "building_condition_score": 5,
        "building_quality_score": 3,
        "construction_type": "Wood",
        "exterior_walls": "wood_siding",
        "fireplace": "false",
        "full_bath_count": 2,
        "garage_parking_of_cars": 1,
        "garage_type_parking": "underground_basement",
        "heating": "forced_air_unit",
        "heating_fuel_type": "gas",
        "no_of_buildings": 1,
        "no_of_stories": 2,
        "number_of_bedrooms": 4,
        "number_of_units": 1,
        "partial_bath_count": 1,
        "pool": "true",
        "property_type": "Single Family Residential",
        "roof_cover": "Asphalt",
        "roof_type": "Wood truss",
        "site_area_acres": 0.119,
        "style": "colonial",
        "total_bath_count": 2.5,
        "total_number_of_rooms": 7,
        "sewer": "municipal",
        "subdivision": "CITY LAND ASSOCIATION",
        "water": "municipal",
        "year_built": 1957,
        "zoning": "RH1"
    },

    "assessment": {
        "apn": "0000 -1111",
        "assessment_year": 2015,
        "tax_year": 2015,
        "total_assessed_value": 1300000.0,
        "tax_amount": 15199.86
    }
}
home_two = {
    "id": 2,
    "property_address": "71 Predovic Meadow, Port Emersonside, SD 41277",
    "property_identifier": "71+Predovic+Meadow&zipcode=41277",
    "property": {
        "air_conditioning": "yes",
        "attic": "false",
        "basement": "full_basement",
        "building_area_sq_ft": 1824,
        "building_condition_score": 5,
        "building_quality_score": 3,
        "construction_type": "Wood",
        "exterior_walls": "wood_siding",
        "fireplace": "false",
        "full_bath_count": 2,
        "garage_parking_of_cars": 1,
        "garage_type_parking": "underground_basement",
        "heating": "forced_air_unit",
        "heating_fuel_type": "gas",
        "no_of_buildings": 1,
        "no_of_stories": 2,
        "number_of_bedrooms": 4,
        "number_of_units": 1,
        "partial_bath_count": 1,
        "pool": "true",
        "property_type": "Single Family Residential",
        "roof_cover": "Asphalt",
        "roof_type": "Wood truss",
        "site_area_acres": 0.119,
        "style": "colonial",
        "total_bath_count": 2.5,
        "total_number_of_rooms": 7,
        "sewer": "municipal",
        "subdivision": "CITY LAND ASSOCIATION",
        "water": "municipal",
        "year_built": 1957,
        "zoning": "RH1"
    },

    "assessment": {
        "apn": "0000 -1111",
        "assessment_year": 2015,
        "tax_year": 2015,
        "total_assessed_value": 1300000.0,
        "tax_amount": 15199.86
    }
}


home_three = {
    "id": 3,
    "property_address": "4553 Haley Stream Apt. 502, Lakinstad, MT 41214",
    "property_identifier": "4553+Haley+Stream+Apt+502&zipcode=41214",
    "property": {
        "air_conditioning": "no",
        "attic": "false",
        "basement": "full_basement",
        "building_area_sq_ft": 1824,
        "building_condition_score": 5,
        "building_quality_score": 3,
        "construction_type": "Wood",
        "exterior_walls": "wood_siding",
        "fireplace": "false",
        "full_bath_count": 2,
        "garage_parking_of_cars": 1,
        "garage_type_parking": "underground_basement",
        "heating": "forced_air_unit",
        "heating_fuel_type": "gas",
        "no_of_buildings": 1,
        "no_of_stories": 2,
        "number_of_bedrooms": 4,
        "number_of_units": 1,
        "partial_bath_count": 1,
        "pool": "true",
        "property_type": "Single Family Residential",
        "roof_cover": "Asphalt",
        "roof_type": "Wood truss",
        "site_area_acres": 0.119,
        "style": "colonial",
        "total_bath_count": 2.5,
        "total_number_of_rooms": 7,
        "sewer": "septic",
        "subdivision": "CITY LAND ASSOCIATION",
        "water": "municipal",
        "year_built": 1957,
        "zoning": "RH1"
    },

    "assessment": {
        "apn": "0000 -1111",
        "assessment_year": 2015,
        "tax_year": 2015,
        "total_assessed_value": 1300000.0,
        "tax_amount": 15199.86
    }
}



home_four = {
    "id": 3,
    "property_address": "375 Buckridge Light Apt. 154, Karlimouth, IA 37545-4100",
    "property_identifier": "375+Buckridge+Light+Apt+154&zipcode=37545",
    "property": {
        "air_conditioning": "no",
        "attic": "false",
        "basement": "full_basement",
        "building_area_sq_ft": 1824,
        "building_condition_score": 5,
        "building_quality_score": 3,
        "construction_type": "Wood",
        "exterior_walls": "wood_siding",
        "fireplace": "false",
        "full_bath_count": 2,
        "garage_parking_of_cars": 1,
        "garage_type_parking": "underground_basement",
        "heating": "forced_air_unit",
        "heating_fuel_type": "gas",
        "no_of_buildings": 1,
        "no_of_stories": 2,
        "number_of_bedrooms": 4,
        "number_of_units": 1,
        "partial_bath_count": 1,
        "pool": "true",
        "property_type": "Single Family Residential",
        "roof_cover": "Asphalt",
        "roof_type": "Wood truss",
        "site_area_acres": 0.119,
        "style": "colonial",
        "total_bath_count": 2.5,
        "total_number_of_rooms": 7,
        "sewer": "septic",
        "subdivision": "CITY LAND ASSOCIATION",
        "water": "municipal",
        "year_built": 1957,
        "zoning": "RH1"
    },

    "assessment": {
        "apn": "0000 -1111",
        "assessment_year": 2015,
        "tax_year": 2015,
        "total_assessed_value": 1300000.0,
        "tax_amount": 15199.86
    }
}